name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install --no-package-lock --legacy-peer-deps
        
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
        
    - name: Build frontend
      run: npm run build
        
    - name: Start app in background
      run: |
        npm start &
        sleep 10  # Wait for app to start
        
    - name: Run Playwright tests
      run: npx playwright test
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report/
