name: Preview Deployment

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/CODEOWNERS'
      - '.github/dependabot.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache-dependency-path: package.json
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install --no-package-lock --legacy-peer-deps
      
    - name: Build frontend
      run: npm run build
      env:
        CI: true
        REACT_APP_API_URL: https://preview-api.nudata.example.com
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/
        
  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.preview_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: build
        
    - name: Set up preview environment
      run: |
        echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        echo "PREVIEW_DOMAIN=pr-${{ github.event.pull_request.number }}.preview.nudata.example.com" >> $GITHUB_ENV
        
    - name: Deploy to preview environment
      id: deploy
      run: |
        # This would be replaced with actual deployment commands
        # For example, using AWS S3 + CloudFront, Vercel, Netlify, etc.
        echo "Deploying to preview environment: ${{ env.PREVIEW_DOMAIN }}"
        # Mock deployment for now
        echo "::set-output name=preview_url::https://${{ env.PREVIEW_DOMAIN }}"
        
    - name: Comment on PR with preview URL
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const previewUrl = process.env.PREVIEW_DOMAIN;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 Preview deployment is ready!\n\nYou can view your changes at: https://${previewUrl}`
          });
